version: "3.7"
services:
  app:
    env_file:
      - ./.env.prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    depends_on:
      - postgres
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    environment:
      NODE_ENV: "production"
      PG_DB_HOST: "postgres"
  postgres:
    image: postgres:11-alpine
    env_file:
      - ./.env.prod
    environment:
      POSTGRES_DB: "${PG_DB}"
      POSTGRES_USER: "${PG_DB_USER}"
      POSTGRES_PASSWORD: "${PG_DB_PASSWORD}"
